version: '3.8'

services:
  bolt-ai:
    image: bolt-ai:production
    build: 
      context: .
      dockerfile: Dockerfile-mine
      target: bolt-ai-production
    ports:
      - ":5173"
    environment:
      # Core Configuration
      - NODE_ENV=production
      - PORT=${BOLT_AI_PORT:-5173}
      - RUNNING_IN_DOCKER=true
      
      # API Keys (will be set in Coolify UI)
      - GROQ_API_KEY=${GROQ_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPEN_ROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      
      # Optional Configurations with defaults
      - OLLAMA_API_BASE_URL=${OLLAMA_API_BASE_URL:-}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL:-debug}
      - DEFAULT_NUM_CTX=${DEFAULT_NUM_CTX:-32768}
      
      # Additional API Keys
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - OPENAI_LIKE_API_BASE_URL=${OPENAI_LIKE_API_BASE_URL}
      - OPENAI_LIKE_API_KEY=${OPENAI_LIKE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - LMSTUDIO_API_BASE_URL=${LMSTUDIO_API_BASE_URL}
      - XAI_API_KEY=${XAI_API_KEY}

    volumes:
      # Persistent storage for application data
      - bolt-ai-data:/app/data
      # Optional: Persistent node_modules cache
      - bolt-ai-node-modules:/app/node_modules
    
    restart: unless-stopped

volumes:
  # Define volumes for persistent storage
  bolt-ai-data:
  bolt-ai-node-modules:
